version: '3'
services:
容器名:
    image: 镜像名
    runtime: nvidia  # 使用 NVIDIA GPU
    ports:
      - "ssh宿主机开放端口:22"
    hostname: 容器主机名
    shm_size: 8g
    pid: host
    command: /bin/bash
    restart: always